package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CommentsAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCommentsAllPropertiesEquals(Comments expected, Comments actual) {
        assertCommentsAutoGeneratedPropertiesEquals(expected, actual);
        assertCommentsAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCommentsAllUpdatablePropertiesEquals(Comments expected, Comments actual) {
        assertCommentsUpdatableFieldsEquals(expected, actual);
        assertCommentsUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCommentsAutoGeneratedPropertiesEquals(Comments expected, Comments actual) {
        assertThat(expected)
            .as("Verify Comments auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCommentsUpdatableFieldsEquals(Comments expected, Comments actual) {
        assertThat(expected)
            .as("Verify Comments relevant properties")
            .satisfies(e -> assertThat(e.getCommentBody()).as("check commentBody").isEqualTo(actual.getCommentBody()))
            .satisfies(e -> assertThat(e.getAuthorUserName()).as("check authorUserName").isEqualTo(actual.getAuthorUserName()))
            .satisfies(e -> assertThat(e.getLikes()).as("check likes").isEqualTo(actual.getLikes()))
            .satisfies(e -> assertThat(e.getDislikes()).as("check dislikes").isEqualTo(actual.getDislikes()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCommentsUpdatableRelationshipsEquals(Comments expected, Comments actual) {
        assertThat(expected)
            .as("Verify Comments relationships")
            .satisfies(e -> assertThat(e.getVideo()).as("check video").isEqualTo(actual.getVideo()));
    }
}
